### ISSUE TITLE
Crashes on resuming

### ISSUE THREAD

**Issue by kazyx** [locana/uwpmm#41]

**Comment by kazyx** [comment]
This issued does not happen on store release version packages

**Comment by kazyx** [comment]
Fixed by stopping StatusObserver and NetworkObserver immediately after onSuspend is called

**Comment by tarmo888** [comment]
Still crashes on resuming.

Nokia Lumia 1520
Locana 1.3.0.0

**Comment by kazyx** [comment]
Could you tell me the procedure?

I can't reproduce this issue now on M8 and Lumia 535.

**Comment by tarmo888** [comment]
1) Open Locana.
2) Wait until the live picture from camera starts showing.
3) Click on Windows button to go to front screen or hold Back button to switch to other opened app.
4) When switching back to Locana from list of opened apps, the "Resuming..." text is shown for a second and Locana closes.
