### ISSUE TITLE
Liveview image from the last camera remains even after connected to another camera

### ISSUE THREAD

**Issue by naotaco** [locana/uwpmm#48]
Log below:

    null,
    null,
    null
  ],
  "id": 29
}
[JpegStreamAnalizer] Detected end of stream.
A first chance exception of type 'System.IO.IOException' occurred in KzImageStream.DLL
[LvProcessor] Caught System.IO.IOException: finish reading loop
[LvProcessor] End of reading loop
PropertyChanged: Status
PropertyChanged: Status
Zoom pos -1
[JpegStreamAnalizer] - - - - 9 FPS - - - -
A first chance exception of type 'System.Exception' occurred in mscorlib.ni.dll
HttpPost Exception:    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Kazyx.RemoteApi.AsyncPostClient.<PostAsync>d__6.MoveNext()
A first chance exception of type 'Kazyx.RemoteApi.RemoteApiException' occurred in KzRemoteApi.DLL
A first chance exception of type 'Kazyx.RemoteApi.RemoteApiException' occurred in mscorlib.ni.dll
A first chance exception of type 'Kazyx.RemoteApi.RemoteApiException' occurred in KzRemoteApi.DLL
A first chance exception of type 'Kazyx.RemoteApi.RemoteApiException' occurred in mscorlib.ni.dll
A first chance exception of type 'Kazyx.RemoteApi.RemoteApiException' occurred in mscorlib.ni.dll
A first chance exception of type 'Kazyx.RemoteApi.RemoteApiException' occurred in mscorlib.ni.dll
GetEvent failed with code: NetworkError
StatusObserver Error limit
StatusObserver: Stop
Not connected to camera device.
LiveviewPage Unloaded
StatusObserver: Stop
[LvProcessor] CloseConnection
NetworkStatusChanged. Unlock stay entrance mode.
NetworkInformation NetworkStatusChanged
Not connected to camera device.
The thread 0xdc4 has exited with code 259 (0x103).
The thread 0x7f8 has exited with code 259 (0x103).
The thread 0x5f4 has exited with code 259 (0x103).
The thread 0x188 has exited with code 259 (0x103).
Not connected to camera device.
The thread 0xd88 has exited with code 259 (0x103).
NetworkStatusChanged. Unlock stay entrance mode.
NetworkInformation NetworkStatusChanged
New access point detected. Refresh.
[SoDiscovery] Search
[SoDiscovery] Search
[SoDiscovery] Send M-Search to DIRECT-X4E0:ILCE-6000
[SoDiscovery] Send M-Search to DIRECT-X4E0:ILCE-6000
[SoDiscovery] HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1800
EXT: 
LOCATION: http://192.168.122.1:61000/scalarwebapi_dd.xml
SERVER: UPnP/1.0 MINT-X/1.8.1
ST: urn:schemas-sony-com:service:ScalarWebAPI:1
USN: uuid:000000001000-1010-8000-7A4B8720F6A2::urn:schemas-sony-com:service:ScalarWebAPI:1

A first chance exception of type 'System.Exception' occurred in mscorlib.ni.dll
[SoDiscovery] Search Timeout
[SoDiscovery] Search Timeout
No devices discovered yet. keep searching.
[SoDiscovery] Search
[SoDiscovery] Search
[SoDiscovery] Send M-Search to DIRECT-X4E0:ILCE-6000
[SoDiscovery] Send M-Search to DIRECT-X4E0:ILCE-6000
[SoDiscovery] HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1800
EXT: 
LOCATION: http://192.168.122.1:61000/scalarwebapi_dd.xml
SERVER: UPnP/1.0 MINT-X/1.8.1
ST: urn:schemas-sony-com:service:ScalarWebAPI:1
USN: uuid:000000001000-1010-8000-7A4B8720F6A2::urn:schemas-sony-com:service:ScalarWebAPI:1

A first chance exception of type 'System.Exception' occurred in mscorlib.ni.dll
[SoDiscovery] Search Timeout
[SoDiscovery] Search Timeout
No devices discovered yet. keep searching.
[SoDiscovery] Search
[SoDiscovery] Search
[SoDiscovery] Send M-Search to DIRECT-X4E0:ILCE-6000
[SoDiscovery] Send M-Search to DIRECT-X4E0:ILCE-6000
[SoDiscovery] HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1800
EXT: 
LOCATION: http://192.168.122.1:61000/scalarwebapi_dd.xml
SERVER: UPnP/1.0 MINT-X/1.8.1
ST: urn:schemas-sony-com:service:ScalarWebAPI:1
USN: uuid:000000001000-1010-8000-7A4B8720F6A2::urn:schemas-sony-com:service:ScalarWebAPI:1

A first chance exception of type 'System.Exception' occurred in mscorlib.ni.dll
The thread 0xc78 has exited with code 0 (0x0).
[SoDiscovery] Search Timeout
[SoDiscovery] Search Timeout
No devices discovered yet. keep searching.
[SoDiscovery] Search
[SoDiscovery] Search
[SoDiscovery] Send M-Search to DIRECT-X4E0:ILCE-6000
[SoDiscovery] Send M-Search to DIRECT-X4E0:ILCE-6000
NetworkStatusChanged. Unlock stay entrance mode.
NetworkInformation NetworkStatusChanged
No devices discovered yet. keep searching.
[SoDiscovery] Search
[SoDiscovery] Search
[SoDiscovery] Send M-Search to DIRECT-X4E0:ILCE-6000
[SoDiscovery] Send M-Search to DIRECT-X4E0:ILCE-6000
[SoDiscovery] HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1800
EXT: 
LOCATION: http://192.168.122.1:61000/scalarwebapi_dd.xml
SERVER: UPnP/1.0 MINT-X/1.8.1
ST: urn:schemas-sony-com:service:ScalarWebAPI:1
USN: uuid:000000001000-1010-8000-7A4B8720F6A2::urn:schemas-sony-com:service:ScalarWebAPI:1

[SoDiscovery] HTTP/1.1 200 OK
CACHE-CONTROL: max-age=1800
EXT: 
LOCATION: http://192.168.122.1:61000/scalarwebapi_dd.xml
SERVER: UPnP/1.0 MINT-X/1.8.1
ST: urn:schemas-sony-com:service:ScalarWebAPI:1
USN: uuid:000000001000-1010-8000-7A4B8720F6A2::urn:schemas-sony-com:service:ScalarWebAPI:1

Show Progress: Preparing connection...
Set up control
ServerVersion: 2.0.1
This is liberated version!!
StatusObserver: Start
StatusObserver: Refresh
{
  "id": 34,
  "result": [
    {
      "type": "availableApiList",
      "names": [
        "getVersions",
        "getMethodTypes",
        "getApplicationInfo",
        "getAvailableApiList",
        "getEvent",
        "startRecMode",
        "stopRecMode"
      ]
    },
    {
      "type": "cameraStatus",
      "cameraStatus": "NotReady"
    },
    null,
    {
      "type": "liveviewStatus",
      "liveviewStatus": false
    },
    null,
    [],
    [],
    null,
    null,
    null,
    [],
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    {
      "type": "postviewImageSize",
      "postviewImageSizeCandidates": [
        "2M"
      ],

**Comment by kazyx** [comment]
Fixed by 8c84109
