### ISSUE TITLE
Feature: Camera orientation detection like in PlayMemories Mobile app

### ISSUE THREAD

**Issue by tarmo888** [locana/uwpmm#63]
When you tilt the camera to portrait orientation, Android app display will change accordingly, but Scrap nor Locana does not. Current workaround is that when I want to make portrait orientation photos, I try to trick the phone to change orientation, but this is very annoying.

I think it's the only thing I miss from Android app. In every other way (especially speed), Scrap and Locana are much better.

Lumia 1520 WP8.1
Locana v1.3.0.0
QX100 v3.00

**Comment by naotaco** [comment]
Thanks for your feedback!

We're trying to implement it for next release.

**Comment by naotaco** [comment]
Done by 44a0f3654e2eb487e244d86de1bfa61cb08bbb48 , 83275f4266826d853af02b5d50a9752f039e5fe6 and 47d2390a4eac21744969ad3648a85fe67077e4eb
